KEY_TERMS = (
    'adaptation',
    'agency mission',
    'air quality',
    'anthropogenic',
    'benefits',
    'brownfield',
    'burden',
    'carbon',
    'clean energy',
    'climate',
    'climate',
    'compliance',
    'cost-effective',
    'costs',
    'dei',
    'deia',
    'deregulatory',
    'diversity'
    'droughts',
    'economic certainty',
    'economic impacts',
    'economics',
    'efficiency',
    'electric vehicle',
    'electric vehicles',
    'emissions',
    'endangered species',
    'energy independence',
    'enforcement',
    'environmental justice',
    'equity',
    'ev',
    'federal customer',
    'fossil fuels',
    'fracking',
    'global warming',
    'glyphosate',
    'greenhouse gases',
    'horizontal drilling',
    'hydraulic fracturing',
    'impacts',
    'inclusion',
    'innovation',
    'jobs',
    'justice',
    'mercury',
    'methane',
    'nuclear',
    'permit',
    'permitting',
    'pesticides',
    'pollution',
    'precautionary',
    'public land',
    'regulatory certainty',
    'renewable',
    'resilience',
    'risk',
    'safe',
    'safety',
    'sensible regulations',
    'storms',
    'sustainability',
    'toxic',
    'transparency',
    'unconventional gas',
    'unconventional oil',
    'water quality',
    'wildfires',
    'state',
    'certainty',
    'proceeding',
    'opinion',
    'federal register',
    'guidance',
)

KEY_TERM_GRAMS = max((len(term.split(' ')) for term in KEY_TERMS))
