KEY_TERMS = (
    'adaptation',
    'agency mission',
    'air quality',
    'anthropogenic',
    'benefits',
    'brownfield',
    'clean energy',
    'climate',
    'climate',
    'compliance',
    'cost-effective',
    'costs',
    'deregulatory',
    'droughts',
    'economic certainty',
    'economic impacts',
    'economics',
    'efficiency',
    'emissions',
    'endangered species',
    'energy independence',
    'enforcement',
    'environmental justice',
    'federal customer',
    'fossil fuels',
    'fracking',
    'global warming',
    'glyphosate',
    'greenhouse gases',
    'horizontal drilling',
    'hydraulic fracturing',
    'impacts',
    'innovation',
    'jobs',
    'mercury',
    'methane',
    'pesticides',
    'pollution',
    'precautionary',
    'regulatory certainty',
    'resilience',
    'risk',
    'safe',
    'safety',
    'sensible regulations',
    'storms',
    'sustainability',
    'toxic',
    'transparency',
    'unconventional gas',
    'unconventional oil',
    'water quality',
    'wildfires',
    'state',
    'certainty',
    'proceeding',
    'opinion',
    'federal register',
    'guidance',
)

KEY_TERM_GRAMS = max((len(term.split(' ')) for term in KEY_TERMS))
