from .normalize import normalize_text

KEY_TERMS = (
    'adaptation',
    'agency mission',
    'air quality',
    'anthropogenic',
    'benefits',
    'brownfield',
    'burden',
    'carbon',
    'certainty',
    'clean energy',
    'clean heavy duty',
    'climate',
    'climate change',
    'compliance',
    'community',
    'cost effective',
    'costs',
    'dei',
    'deia',
    'deregulatory',
    'disadvantaged',
    'diversity',
    'droughts',
    'economic certainty',
    'economic impacts',
    'economics',
    'efficiency',
    'electric vehicle',
    'electric vehicles',
    'embodied green house gas',
    'embodied greenhouse gas',
    'emissions',
    'endangered species',
    'energy independence',
    'enforcement',
    'environmental justice',
    'environmental quality',
    'equity',
    'ev',
    'federal customer',
    'federal register',
    'fossil fuels',
    'fracking',
    'global warming',
    'glyphosate',
    'green house gas'
    'green house gases'
    'greenhouse gas',
    'greenhouse gases',
    'guidance',
    'horizontal drilling',
    'hydraulic fracturing',
    'impacts',
    'inclusion',
    'innovation',
    'jobs',
    'justice',
    'mercury',
    'methane',
    'net zero',
    'nuclear',
    'opinion',
    'permit',
    'permitting',
    'pesticides',
    'pollution',
    'precautionary',
    'proceeding',
    'public land',
    'regulatory certainty',
    'renewable',
    'resilience',
    'risk',
    'safe',
    'safety',
    'sensible regulations',
    'state',
    'storms',
    'sustainability',
    'toxic',
    'transparency',
    'unconventional gas',
    'unconventional oil',
    'underserved',
    'water quality',
    'wildfires',

    # Español
    'clima',
    'climática',
    'climático',
)

# Ensure key terms are normalized in the same way as our text will be.
KEY_TERMS = list(set(normalize_text(term) for term in KEY_TERMS))

KEY_TERM_GRAMS = max((len(term.split(' ')) for term in KEY_TERMS))
